# -*- coding: utf-8 -*-

"""
    This file contains final aggregated settings for the project.
    Do NOT edit this file manually.
    All changes should be done in files base.py or local.py or /usr/local/etc/irsexpress2.yaml

    Settings get overridden in this order:
    base.py -> (development/production).py -> local.py -> /usr/local/etc/[appname].yaml -> settings.py
    Most secret and server-specific settings should reside in .yaml file.
    Other files are stored in repository
"""

import os
import yaml
from .local import *

with open(LOCAL_SETTINGS_FILE, 'r') as sf:
    ysettings = yaml.load(sf.read())

from .logging_settings import LOGGING, LOG_FOLDER
