FROM ubuntu:bionic

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1 C_FORCE_ROOT=true

WORKDIR /opt/staticbuilder

RUN DEBIAN_FRONTEND=noninteractive \
    && apt update \
    && apt install -y \
        curl \
        python3 python3-distutils python3-lxml \
        libxml2-dev libxslt-dev libjpeg-dev libpng-dev libfreetype6-dev zlibc zlib1g-dev libpq-dev \
        npm \
    && cd /tmp/ && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py && cd - \
    && npm install gulp -g

COPY config/gulp/default_packages.json ./package.json
RUN npm install
COPY config/gulp/package.json ./package.json
RUN npm install
COPY config/pip/requirements.txt requirements.txt
RUN pip3 --no-cache-dir install -U -r requirements.txt

COPY config/build_static.sh ./
ENTRYPOINT ["/bin/bash", "build_static.sh"]
